### PR TITLE
Add RepeatBehaviour to animations

### PR DESCRIPTION
**Pull request by JDemortier**
Animations are quite easily configured with your library but I wanted to able to make them loop in my application.

I simply added *RepeatBehavior* to *ITransitionParams* and transmitted this option to the animations when needed. I edited the test app to show the new behavior and to check the previous behavior (no repeat) was still working as intended.

I hope this can be useful.

Best regards,
Jeremy

### CODE REVIEW

**Comment by andyb1979** [comment]
Cool, thanks!

**Comment by JDemortier** [comment]
You're welcome. Do you plan to make a new nuget package or should I do it locally?

**Comment by andyb1979** [comment]
I'll do it today!

**Comment by SciChartTeam** [comment]
Should be done now. Thanks for contributing!

**Comment by JDemortier** [comment]
I didn't do much to be honest. Most of the code was already present ;)

Thanks for the package!

**Pull request merged**
